name: Invidious Pinger

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_pinger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Invidious Pinger
        run: |
          python invidious_pinger.py

      - name: Commit instances.json file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add instances.json
          git commit -m "Update instances.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
